In [1]:
import torch

In [4]:
x = torch.empty(2,3)
print(x)

tensor([[7.5014e+28, 2.6217e+20, 1.6488e+22],
        [1.7751e+28, 1.8524e+28, 9.1042e-12]])


In [5]:
x = torch.rand(2,2)
print(x)

tensor([[0.5904, 0.0352],
        [0.9367, 0.0451]])


In [6]:
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
x = torch.ones(2,3)
print(x.dtype)
x

torch.float32


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
x = torch.ones(3,2, dtype = torch.int)
x.dtype
x

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

In [17]:
x = torch.rand(2,2)
x.dtype
x.size()
x

tensor([[0.7441, 0.0135],
        [0.2442, 0.0582]])

In [18]:
x = torch.tensor([1.3 , 0.1])
x

tensor([1.3000, 0.1000])

In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x + y
z = torch.add(x,y)
z

tensor([[0.2543, 0.2511],
        [1.5713, 0.6631]])

In [23]:
x = torch.rand(2,2)
y = torch.rand(2,2)
y.add_(x)
print(y)

z = torch.sub(x, y)
print(z)

tensor([[1.7984, 1.1606],
        [1.1572, 1.1675]])
tensor([[-0.9299, -0.5861],
        [-0.3933, -0.2428]])


In [24]:
x = torch.rand(2,2)
y = torch.rand(2,2)
y.mul_(x)
y

tensor([[0.7208, 0.1812],
        [0.5215, 0.1904]])

In [32]:
x = torch.rand(5,4)
print(x)
print(x[:,0:2])
print(x[1,:])
print(x[1,1])
print(x[1,1].item()) #item() method just for a scaler

tensor([[0.1971, 0.0392, 0.5375, 0.1076],
        [0.4260, 0.7964, 0.7769, 0.4668],
        [0.3892, 0.3364, 0.4895, 0.5005],
        [0.2446, 0.3021, 0.3094, 0.9895],
        [0.1703, 0.9577, 0.0662, 0.8515]])
tensor([[0.1971, 0.0392],
        [0.4260, 0.7964],
        [0.3892, 0.3364],
        [0.2446, 0.3021],
        [0.1703, 0.9577]])
tensor([0.4260, 0.7964, 0.7769, 0.4668])
tensor(0.7964)
0.7963874340057373


In [36]:
x =torch.rand(4,4)
print(x)
y = x.view(16,1)
print(y)

tensor([[0.7505, 0.2990, 0.1306, 0.2413],
        [0.8692, 0.5092, 0.6348, 0.0413],
        [0.7388, 0.2177, 0.1314, 0.5781],
        [0.1798, 0.9838, 0.2237, 0.5627]])
tensor([[0.7505],
        [0.2990],
        [0.1306],
        [0.2413],
        [0.8692],
        [0.5092],
        [0.6348],
        [0.0413],
        [0.7388],
        [0.2177],
        [0.1314],
        [0.5781],
        [0.1798],
        [0.9838],
        [0.2237],
        [0.5627]])
